[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules']
solc = '0.8.20'
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
localhost = "http://localhost:8545"
polygon = "${POLYGON_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
