version: '3.9'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh:ro
    command: sleep infinity
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - HARDHAT_RPC_URL=http://hardhat-node:8545
    depends_on:
      - postgres
      - redis
      - hardhat-node
      - mailhog
